### ISSUE TITLE
Docker-compose is not working

### ISSUE THREAD

**Issue by aiveras** [cross-solution/YAWIK#536]
we have tried to get Yawik to run with docker-compose but unfortunately a number of errors are displayed. These are caused as far as we can see in docker-entrypoint.sh references files and commands that are not available inside the container built from the provided Dockerfile.
Besides the docker-compose file we copied the .env file and the whole folder etc from the repo.

```
version: "3"
services:
    nginx:
        image: nginx:alpine
        container_name: yawik-nginx
        volumes:
            - ./etc/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - /opt/docker/yawik/public:/var/www/yawik
        ports:
            - "8080:80"
        links:
            - php
            - mongo
        environment:
            - UMASK="0000"
            - VIRTUAL_HOST= domain.tld
            - LETSENCRYPT_HOST= domain.tld
            - LETSENCRYPT_EMAIL= email@example.com
        networks:
            - default
            - proxy-tier

    php:
        container_name: yawik-php
        env_file:
          - .env
        build:
            context: etc/docker/php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - /opt/docker/yawik/public:/var/www/yawik
        links:
            - mongo
        environment:
            - UMASK=0000
        networks:
            - proxy-tier
            - default

    mongo:
        image: mongo:3.4.10
        container_name: yawik-mongo
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - /opt/docker/yawik/mongodb/data:/data/db
        ports:
            - "27017:27017"
        command: mongod --smallfiles --logpath=/dev/null # --quiet


networks:

  proxy-tier:
    external:
      name: nginx-proxy

```

As error message we get the following displayed:

```
Attaching to yawik-mongo, yawik-php, yawik-nginx
yawik-php | /var/www/yawik
yawik-nginx | 2019/03/19 14:35:16 [emerg] 1#1: host not found in upstream "php" in /etc/nginx/conf.d/default.conf:11
yawik-nginx | nginx: [emerg] host not found in upstream "php" in /etc/nginx/conf.d/default.conf:11
yawik-php exited with code 1
yawik-nginx exited with code 1
```
